import type { DogProfile } from "./types";

// Synthetic fixture data for the public portfolio repo.
// The private prototype used live rescue listings; this file keeps the demo
// runnable without redistributing third-party listing text or images.
export const dogs: DogProfile[] = [
  {
    id: "demo-1",
    name: "Scout",
    breed: "Border Collie mix",
    ageYears: 2.4,
    ageLabel: "2 years 5 months",
    gender: "Male",
    weightKg: 21,
    location: "Melbourne, VIC",
    state: "VIC",
    postcode: "3000",
    lat: -37.8136,
    lng: 144.9631,
    description:
      "Scout is a bright, athletic dog who loves training games, long walks, and having a clear job to do. He is affectionate with people he knows and would suit an adopter who enjoys structure, enrichment, and active weekends.",
    photos: [],
    petrescueUrl: "https://example.com/fetchmatch/demo-scout",
    rescueOrg: "Demo Rescue Network",
    adoptionFee: "Demo listing",
    classification: {
      energy: { physical: "very_high", mental: "high" },
      attachment: { bondingStyle: "loyal", aloneTimeTolerance: "some_time", separationAnxiety: false },
      strangerConfidence: "warming_up",
      household: { minKidAge: 12, dogCompatibility: "conditional", dogNotes: "Best with calm introductions", catCompatibility: "untested" },
      reactivity: { leashReactive: false, fearBased: false, preyDrive: true, resourceGuarding: false, overallLevel: "mild" },
      training: { level: "knows_basics", housetrained: true, crateTrained: true, leashManners: "learning", recall: "developing", foodMotivated: true },
      living: { needsYard: true, fencingMinMetres: 1.5, indoorRequired: true, suitableForApartment: false, lowStairs: false, escapeRisk: false },
      size: "medium",
      summary: "Scout is a high-drive learner who would thrive with an active adopter who enjoys training and outdoor time.",
      classificationConfidence: "high",
    },
  },
  {
    id: "demo-2",
    name: "Miso",
    breed: "Greyhound",
    ageYears: 5.8,
    ageLabel: "5 years 10 months",
    gender: "Female",
    weightKg: 27,
    location: "Geelong, VIC",
    state: "VIC",
    postcode: "3220",
    lat: -38.1499,
    lng: 144.3617,
    description:
      "Miso is a gentle couch companion who enjoys short walks, soft beds, and quiet routines. She warms up politely to new people and would suit an apartment or small-yard home with predictable days.",
    photos: [],
    petrescueUrl: "https://example.com/fetchmatch/demo-miso",
    rescueOrg: "Demo Rescue Network",
    adoptionFee: "Demo listing",
    classification: {
      energy: { physical: "low", mental: "moderate" },
      attachment: { bondingStyle: "loyal", aloneTimeTolerance: "independent", separationAnxiety: false },
      strangerConfidence: "warming_up",
      household: { minKidAge: 8, dogCompatibility: "conditional", dogNotes: "Prefers calm dogs", catCompatibility: "no" },
      reactivity: { leashReactive: false, fearBased: false, preyDrive: true, resourceGuarding: false, overallLevel: "mild" },
      training: { level: "knows_basics", housetrained: true, crateTrained: false, leashManners: "good", recall: "unknown", foodMotivated: false },
      living: { needsYard: false, fencingMinMetres: null, indoorRequired: true, suitableForApartment: true, lowStairs: true, escapeRisk: false },
      size: "large",
      summary: "Miso is a calm, low-energy companion suited to a quieter home and relaxed daily routine.",
      classificationConfidence: "high",
    },
  },
  {
    id: "demo-3",
    name: "Poppy",
    breed: "Cavoodle",
    ageYears: 1.3,
    ageLabel: "1 year 4 months",
    gender: "Female",
    weightKg: 8,
    location: "Ballarat, VIC",
    state: "VIC",
    postcode: "3350",
    lat: -37.5622,
    lng: 143.8503,
    description:
      "Poppy is a cheerful small dog who likes company, gentle play, and being included in family life. She is still learning confidence when left alone and would do best where someone is home often.",
    photos: [],
    petrescueUrl: "https://example.com/fetchmatch/demo-poppy",
    rescueOrg: "Demo Rescue Network",
    adoptionFee: "Demo listing",
    classification: {
      energy: { physical: "moderate", mental: "moderate" },
      attachment: { bondingStyle: "velcro", aloneTimeTolerance: "needs_company", separationAnxiety: true },
      strangerConfidence: "friendly",
      household: { minKidAge: 5, dogCompatibility: "yes", dogNotes: "Enjoys friendly small dogs", catCompatibility: "conditional" },
      reactivity: { leashReactive: false, fearBased: false, preyDrive: false, resourceGuarding: false, overallLevel: "none" },
      training: { level: "learning", housetrained: true, crateTrained: false, leashManners: "learning", recall: "learning", foodMotivated: true },
      living: { needsYard: false, fencingMinMetres: null, indoorRequired: true, suitableForApartment: true, lowStairs: false, escapeRisk: false },
      size: "small",
      summary: "Poppy is an affectionate small dog who suits a home with time for companionship and basic training.",
      classificationConfidence: "medium",
    },
  },
  {
    id: "demo-4",
    name: "Atlas",
    breed: "Mastiff mix",
    ageYears: 4.1,
    ageLabel: "4 years 1 month",
    gender: "Male",
    weightKg: 42,
    location: "Bendigo, VIC",
    state: "VIC",
    postcode: "3550",
    lat: -36.757,
    lng: 144.2794,
    description:
      "Atlas is a steady, affectionate large dog who enjoys slow walks, food puzzles, and lounging near his people. He needs secure fencing and an adopter comfortable handling a bigger dog.",
    photos: [],
    petrescueUrl: "https://example.com/fetchmatch/demo-atlas",
    rescueOrg: "Demo Rescue Network",
    adoptionFee: "Demo listing",
    classification: {
      energy: { physical: "moderate", mental: "low" },
      attachment: { bondingStyle: "loyal", aloneTimeTolerance: "some_time", separationAnxiety: false },
      strangerConfidence: "friendly",
      household: { minKidAge: 12, dogCompatibility: "conditional", dogNotes: "Needs size-aware introductions", catCompatibility: "untested" },
      reactivity: { leashReactive: false, fearBased: false, preyDrive: false, resourceGuarding: false, overallLevel: "none" },
      training: { level: "knows_basics", housetrained: true, crateTrained: false, leashManners: "needs_work", recall: "developing", foodMotivated: true },
      living: { needsYard: true, fencingMinMetres: 1.8, indoorRequired: true, suitableForApartment: false, lowStairs: false, escapeRisk: true },
      size: "extra_large",
      summary: "Atlas is a gentle large dog for an adopter who can offer space, secure fencing, and confident handling.",
      classificationConfidence: "high",
    },
  },
  {
    id: "demo-5",
    name: "Juniper",
    breed: "Kelpie mix",
    ageYears: 0.7,
    ageLabel: "8 months",
    gender: "Female",
    weightKg: 14,
    location: "Shepparton, VIC",
    state: "VIC",
    postcode: "3630",
    lat: -36.3805,
    lng: 145.3987,
    description:
      "Juniper is a young, playful dog who needs puppy foundations, exercise, and patient training. She is social, food motivated, and best suited to an adopter ready for a busy adolescent dog.",
    photos: [],
    petrescueUrl: "https://example.com/fetchmatch/demo-juniper",
    rescueOrg: "Demo Rescue Network",
    adoptionFee: "Demo listing",
    classification: {
      energy: { physical: "high", mental: "high" },
      attachment: { bondingStyle: "loyal", aloneTimeTolerance: "some_time", separationAnxiety: false },
      strangerConfidence: "friendly",
      household: { minKidAge: 8, dogCompatibility: "yes", dogNotes: "Playful with matched-energy dogs", catCompatibility: "untested" },
      reactivity: { leashReactive: false, fearBased: false, preyDrive: false, resourceGuarding: false, overallLevel: "none" },
      training: { level: "fresh_start", housetrained: false, crateTrained: false, leashManners: "learning", recall: "learning", foodMotivated: true },
      living: { needsYard: true, fencingMinMetres: 1.5, indoorRequired: true, suitableForApartment: false, lowStairs: false, escapeRisk: false },
      size: "medium",
      summary: "Juniper is a smart adolescent dog who needs exercise, structure, and someone excited to keep teaching her.",
      classificationConfidence: "medium",
    },
  },
  {
    id: "demo-6",
    name: "Biscuit",
    breed: "Miniature Schnauzer mix",
    ageYears: 9.2,
    ageLabel: "9 years 2 months",
    gender: "Male",
    weightKg: 9,
    location: "Melbourne, VIC",
    state: "VIC",
    postcode: "3000",
    lat: -37.8136,
    lng: 144.9631,
    description:
      "Biscuit is a senior small dog who likes gentle walks, routine, and quiet affection. He does best with patient handling and would suit someone looking for a lower-energy companion.",
    photos: [],
    petrescueUrl: "https://example.com/fetchmatch/demo-biscuit",
    rescueOrg: "Demo Rescue Network",
    adoptionFee: "Demo listing",
    classification: {
      energy: { physical: "low", mental: "low" },
      attachment: { bondingStyle: "one_person", aloneTimeTolerance: "some_time", separationAnxiety: false },
      strangerConfidence: "needs_time",
      household: { minKidAge: 18, dogCompatibility: "conditional", dogNotes: "Prefers quiet dogs", catCompatibility: "yes" },
      reactivity: { leashReactive: false, fearBased: true, preyDrive: false, resourceGuarding: false, overallLevel: "manageable" },
      training: { level: "well_trained", housetrained: true, crateTrained: false, leashManners: "good", recall: "unknown", foodMotivated: true },
      living: { needsYard: false, fencingMinMetres: null, indoorRequired: true, suitableForApartment: true, lowStairs: true, escapeRisk: false },
      size: "small",
      summary: "Biscuit is a quiet senior suited to an adult home that can give him patience and predictable routines.",
      classificationConfidence: "medium",
    },
  },
];
